[tool.bumpver]
current_version = "1.13.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "chore: Bump version {old_version} -> {new_version}"
commit = true
fetch = true
tag = true
push = true

[tool.bumpver.file_patterns]
"composer.json" = [
    '"version": "{version}",',
]
"README.md" = [
    '- **Two Gateway Module Version**: {version}',
]
"etc/module.xml" = [
    'setup_version="{version}"',
]
